name: Terraform-workaroud
on: push
jobs:
    terraform:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v4

          - name: Set up Terraform
            uses: hashicorp/setup-terraform@v3
            with:
               terraform_version: 1.1.7
            

          - name: Terraform Initialize
            run: terraform init -backend-config "access_key=${{ secrets.AWS_ACCESS_KEY }}" -backend-config "secret_key=${{ secrets.AWS_SECRET_KEY }}"

          - name: Terraform Plan 
            run: terraform plan
            env:
              access_key: ${{ secrets.AWS_ACCESS_KEY }}
              secret_key: ${{ secrets.AWS_SECRET_KEY }}

          - name: Terraform Apply
            run: terraform apply -auto-approve
            env:
              access_key: ${{ secrets.AWS_ACCESS_KEY }}
              secret_key: ${{ secrets.AWS_SECRET_KEY }}
